version: "3.8"

services: 
  postgres:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      
    ports: 
      - 5432:5432
    volumes:
     - './postgres_data:/var/lib/postgresql/data'
     - './pgdata/my-postgres.conf:/etc/postgresql/postgresql.conf'
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "88:80"
    depends_on: 
      - postgres
    
  
  
  